name: Checking for updates...
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: it_IT.UTF-8
        run: |
            sudo locale-gen it_IT.UTF-8
            sudo update-locale LANG=it_IT.UTF-8
      - name: Run script
        env:
          FTPHOST: ${{ secrets.FTPHOST }}
          FTPUSER: ${{ secrets.FTPUSER }}
          FTPPASSWORD: ${{ secrets.FTPPASSWORD }}
          PUSHAUTH: ${{ secrets.PUSHAUTH }}
          PUSHID: ${{ secrets.PUSHID }}
          TELEGRAMID: ${{ secrets.TELEGRAMID }}
          FACEBOOKTOKEN: ${{ secrets.FACEBOOKTOKEN }}
          FACEBOOKID: ${{ secrets.FACEBOOKID }}
        run: |
          python updater.py